apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvs-api-deployment
  labels:
    app: kvs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kvs-api
  template:
    metadata:
      labels:
        app: kvs-api
    spec:
      containers:
      - name: kvs-api
        image: jaimefreire/kvs-api:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: kvs-api-service
spec:  
  selector:
    app: kvs-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
  type: LoadBalancerg