# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TEST_API_CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
  
    name: test-${{ matrix.os }}-${{ matrix.python }}
    runs-on: "${{ matrix.os }}"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        python: [3.6, 3.7, 3.8, 3.9, 3.10]  

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}    
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --extend-exclude=versioneer.py,_version.py,setup.py
       
    - name: Test with pytest
      run: |
        pytest
